version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
     # - run: npm test
  ship: 
  deploy:
  return done
workflows:
  version: 2
  build_test_ship_deploy:
    jobs:
      - build
      - test:
        requires:
          - build
      - ship:
        requires:
          - build
          - test  
      - deploy:
        type: approval
        requires:
          - build
          - test
          - ship
